### ISSUE TITLE
R-Value

### ISSUE THREAD

**Issue by Suplanus** [marcelrebmann/corona-widget-ios#1]
I know there is not much space but the R-value would be great for both configurations.

Thanks for your great work 💖

**Comment by marcelrebmann** [comment]
Thank you! 🙃 
The R-value will at least be integrated in the infections (INF) mode widget as it is a country-wide metric.
I will release this one soon.

The idea of the incidence-mode widget is, that it focuses more on district/state level data. 
Integrating the country level R-value would break this consistency a bit.
I could not find any R-value estimations for single states in the data provided by RKI (would have been nice).
But as there is some space left in this widget mode, maybe another district/state level metric can be displayed here.

**Comment by marcelrebmann** [comment]
I'll close this issue, as the R-value has been integrated in the latest version.
https://github.com/marcelrebmann/corona-widget-ios/releases/tag/v1.1.0
