### ISSUE TITLE
Daten sind falsch 

### ISSUE THREAD

**Issue by tonmar77** [marcelrebmann/corona-widget-ios#13]
Inzidenz und Anzahl Neuinfektionen sind nicht mehr korrekt. 
![431F3934-3C01-4319-AE9A-BAAC075498DD](https://user-images.githubusercontent.com/73377111/127738032-cf9fb4e1-cd30-4577-b10b-2b919f0b8ee6.jpeg)

**Comment by marcelrebmann** [comment]
War wohl ein RKI-Problem, das dort im Nachgang korrigiert wurde
