### ISSUE TITLE
XXL Widget Tablett

### ISSUE THREAD

**Issue by heiweb5** [marcelrebmann/corona-widget-ios#15]
Hallo Marcel,

erst einmal vielen Dank für das Erstellen des Widgets. Ich mag und nutze es sehr gerne.

Seit Neuem gibt es bei Scriptable ja das XXL Widget. Leider zeigt dieses Widget bei deinem Script nicht alles an.

Wäre es möglich, dies anzupassen?

Hier mal zwei Fotos:

Widget Medium:
![image](https://user-images.githubusercontent.com/100371358/157864061-9136a2c5-f1e6-4566-8b33-3639d4295ffe.jpeg)

Hier Widget XXL:
![image](https://user-images.githubusercontent.com/100371358/157864107-1f1c1e36-7139-4456-bcab-6ba7f70ad5b3.jpeg)

Wäre klasse, wenn das umzusetzen wäre. Ich danke dir schonmal im Voraus...

**Comment by marcelrebmann** [comment]
Hey,

freut mich, dass das Widget dir nützlich ist.

Die XXL-Version sollte kein großes Problem sein, das schaue ich mir an.
Außerdem sehe ich, dass bei deinem Gerät die Schriftgröße manchmal etwas zu groß ist (bspw Inzidenz Bundesland / DE). Das schaue ich mir auch mal an - welches iPad nutzt du denn?

**Comment by heiweb5** [comment]
Hi,

vielen Dank... 👍🏻

Ich nutze aktuell das iPad 4 Mini von  Apple...

**Comment by marcelrebmann** [comment]
Habe hier ein paar Anpassungen gemacht:
https://raw.githubusercontent.com/marcelrebmann/corona-widget-ios/feature/widget-size-large-xxl/incidence.js

Probiere es gerne mal aus und gib mir Bescheid, ob es bei dir ebenfalls funktioniert! :)

**Comment by heiweb5** [comment]
Erst einmal vielen Dank fürs Ändern des Scrips…
Sieht schonmal besser aus… Habe es dir mal hier angehängt…

___________________________________
Mit freundlichen Grüßen
Heiko Weber
Am 25. März 2022, 22:04 +0100 schrieb Marcel ***@***.***>:

**Comment by heiweb5** [comment]
Erst einmal vielen Dank fürs Ändern des Scrips…
Sieht schonmal besser aus… Habe es dir mal hier angehängt…

![image](https://user-images.githubusercontent.com/100371358/160212288-e8b58aaa-8b66-4280-89df-17950ec8bf1c.jpeg)
