### ISSUE TITLE
Fehler nach Update

### ISSUE THREAD

**Issue by cl4udiu5** [marcelrebmann/corona-widget-ios#17]
Parameter INF geht nach Update nicht mehr. 

![23FBF952-B87A-49CD-96AA-1F8F4057F834](https://user-images.githubusercontent.com/74124378/160683441-d043e24d-f046-44e3-af18-a9731d05460e.jpeg)
![BFB2BD33-A4ED-4326-A31E-326FBFB7BBCF](https://user-images.githubusercontent.com/74124378/160683443-48ae1ec3-8f4d-4f7f-9d7e-93852413cf89.jpeg)

**Comment by marcelrebmann** [comment]
Hi,
ist mit der gerade veröffentlichten Version 1.4.1 behoben!
Da hat sich ein Fehler beim Datenabruf eingeschlichen :)
