### ISSUE TITLE
Bug Version Clean Install

### ISSUE THREAD

**Issue by balu94** [marcelrebmann/corona-widget-ios#4]
Hi Marcel,

habe gerade das Widget frisch auf dem iPad installiert. Hierbei kam folgende Fehlermeldung. Konnte den Bug nicht beheben. Muss aber wohl am Caching liegen, denn wenn die Methode loadLocation, die aktuelle Position zurückgibt, funktioniert das Widget. 

Fehlermeldung 
2021-01-25 21:47:27: Error on line 670:76: TypeError: null is not an object (evaluating 'lastKnownLocation.latitude')

**Comment by marcelrebmann** [comment]
Hi Simon,

das sollte so nicht sein, das stimmt.
Ich hab nach einem kurzen check evtl. schon den Fehler gefunden - probier das gerne mal aus! Hier der Link zur Branch:
https://github.com/marcelrebmann/corona-widget-ios/blob/bugfix/location-cache/incidence.js

**Comment by balu94** [comment]
Danke, der Bug ist mit der Anpassung behoben 😊

**Comment by marcelrebmann** [comment]
Top! :)
