### ISSUE TITLE
Impfquoten nicht mehr aktualisiert

### ISSUE THREAD

**Issue by larstn1-github** [marcelrebmann/corona-widget-ios#8]
Seit sein paar Tagen (mid 4) werden die Impfquoten nicht mehr aktualisiert. Der rest funktioniert noch super.
Die gesamt Dtl Daten und die Kreis Daten der Impfquoten sind betroffen. 
![image](https://user-images.githubusercontent.com/73709545/114593222-2086ed00-9c8c-11eb-8ee3-920593d780b0.jpeg)

**Comment by marcelrebmann** [comment]
Das RKI hat das Format der Report-Datei geändert, daher schlägt das Update fehl. Ich arbeite schon an einem Fix, den ich die Tage live schalte. Ein Update des Skripts ist da also nicht nötig :)

**Comment by marcelrebmann** [comment]
Der Fix ist live und die Impfquoten sollten im Widget nun automatisch wieder aktualisiert sein.

**Comment by larstn1-github** [comment]
Dank für den Fix, der hat auch ein paar Tage funktioniert, leider jetzt nicht mehr.

**Comment by marcelrebmann** [comment]
Aktuell stimmt es wieder, ohne eine weitere Änderung.
Ich beobachte das in den nächsten Tagen mal und lasse das Issue solange offen.

**Comment by larstn1-github** [comment]
Danke - ich sehe jetzt auch wieder Zahlen, allerdings stimmen die nicht mit https://impfdashboard.de überein. Dort wurden 535.198 Erstimpfungen gemeldet, in widget allerdings 860.400.
Sonst hat das eigentlich immer übereingestimmt - glaube ich zumindest.

![image](https://user-images.githubusercontent.com/73709545/115584669-3d927000-a2cb-11eb-9211-ecf6cce63a2f.jpeg)

**Comment by larstn1-github** [comment]
Heute (22.4) habe ich 689.042 auf impfdashboard.de und 643.600 im Widget. Sind diese Differenzen erwartet/erklärbar, oder ein bug?
Danke!

**Comment by marcelrebmann** [comment]
Nach etwas Debugging habe ich den Fehler gefunden, denke ich.

Die 689.042 des Impfdashboards sind die neu verabreichten Impfungen pro Tag (**Erstimpfungen + Zweitimpfungen** zusammen). Im RKI Report vom 22.04. (heute) ist die Zahl so auch ersichtlich. Den Screenshot hab ich zum Verständnis angehängt. 

Im Widget stehen die verabreichten **Erstimpfungen** pro Tag. Daher ist zu erwarten, dass sich die Werte unterscheiden.
Aus dem Screenshot geht aber auch hervor, dass es eigentlich 621.755 Erstimpfungen heute waren -> Ergo ist hier ein Bug.

<img width="426" alt="Bildschirmfoto 2021-04-22 um 21 21 56" src="https://user-images.githubusercontent.com/20436111/115774525-fd59ed00-a3b1-11eb-894d-17d64a322a00.png">


Mögliche Ursache:
Das Widget berechnet die Anzahl der Erstimpfungen pro Tag aus den Erstimpfungen der einzelnen Bundesländer.
Für die Bundesländer werden ja ebenfalls die Erstimpfungen pro Tag angezeigt.
Nun ist seit kurzem aber im Report für die Bundesländer noch `Impfzentren Bund` als Posten auf. Der wird im Widget noch nicht mit einberechnet, wird aber natürlich immer größer. (siehe Screenshot unten)
Ich denke, das führt zu dem Unterschied von 621k <-> 643k für Deutschland.

<img width="991" alt="Bildschirmfoto 2021-04-22 um 21 33 31" src="https://user-images.githubusercontent.com/20436111/115775098-b5879580-a3b2-11eb-96f3-72b43200fe20.png">

Die Anzahl der Erstimpfungen für gesamt DE werde ich in Zukunft direkt aus der Tabelle aus dem oberen Screenshot nehmen - das ist in progress und sollte demnächst wieder richtig angezeigt werden. Update des Skripts ist dazu wie zuvor nicht nötig.

**Comment by larstn1-github** [comment]
Vielen dank für die ausführliche Erklärung!
Top!!

**Comment by larstn1-github** [comment]
Irgendwie ist noch der Wurm drin. Heute morgen gab das widget on das wir O (Zero) Impfungen hatten. Eventuell waren noch nicht die neuen Zahlen verfügbar?
Später aber dann zeige es 1M Impfungen also 1.000.000 - schön wär es, aber leider nicht korrekt.

Morgens
![image](https://user-images.githubusercontent.com/73709545/115957174-3bb1f200-a501-11eb-9de1-87dd9630d172.jpeg)

Mittag
![image](https://user-images.githubusercontent.com/73709545/115957184-4c626800-a501-11eb-8eb7-b33f5d18b51a.jpeg)

**Comment by marcelrebmann** [comment]
Dass es noch nicht passt, war zu erwarten - der Fix war noch nicht live. Ab der nächsten Aktualisierung seitens des RKI sollte es dann aber korrekt angezeigt werden.

**Comment by GePlusE** [comment]
Mir ist aufgefallen, dass sich die Impfquote seit mehreren Tagen wieder nicht aktualisiert. Es gibt auch den Hinweis daneben, dass die Aktualisierung wohl nicht stimmt. 

![image](https://user-images.githubusercontent.com/59800240/135230579-a16b0af1-4c56-45d1-8e3e-0f9cd2abbb0e.jpeg)

**Comment by marcelrebmann** [comment]
@GePlusE das Format des RKI-Reports hat sich mal wieder leicht geändert. Ich schaue es mir die Tage an, danke für den Hinweis!
