### ISSUE TITLE
Größe passt nicht

### ISSUE THREAD

**Issue by twil1305** [marcelrebmann/corona-widget-ios#9]
![D549EB49-B452-489A-AD15-329BEB1F9A54](https://user-images.githubusercontent.com/76752584/114843629-4d491a80-9dda-11eb-80aa-0c3c04911ff0.jpeg)

**Comment by twil1305** [comment]
Auf meinem iPhone SE1 passen die Daten nicht auf den Bildschirm. 
Kann man das anpassen?

**Comment by marcelrebmann** [comment]
Das iPhone SE mit 4" Bildschirmdiagonale nehme ich an?
Hast du den Anzeigezoom am iPhone eingestellt und so alle Elemente vergrößert? (https://support.apple.com/de-de/guide/iphone/iphd6804774e/ios)

Unabhängig davon kannst du in der aktuellsten Version (Version 1.2.1) nun einen Skalierungsfaktor (`CONFIG` -> `fontScaleFactor`) angeben, der die Schriftgrößen entsprechend vergrößert/verkleinert.
Außerdem können auch alle einzelnen Schriftgrößen unter `CONFIG` angepasst werden.

Gerne mal ausprobieren und Bescheid geben, was am besten funktioniert hat.
